-- ============================================================================
-- ZIP Competitive Puzzle Platform — Database Schema
-- Migration: 003_add_walls
-- Add walls column to puzzles table so tournament puzzles store the same
-- wall segments produced by PuzzleEngine.generate() (same as practice mode).
-- ============================================================================

ALTER TABLE puzzles
  ADD COLUMN IF NOT EXISTS walls JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN puzzles.walls IS 'Array of wall segments [{x, y, length, isVertical}] generated by PuzzleEngine';
